spring.application.name=LogScope

# Veritabanı adı ve nerede çalışacağı (Hafızada çalışsın istiyoruz)
spring.datasource.url=jdbc:h2:mem:logscopedb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

# H2 Konsolu: Tarayıcıdan http://localhost:8080/h2-console yazınca veritabanını görebilelim.
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Uygulama her açıldığında tabloları otomatik güncelle/oluştur
spring.jpa.hibernate.ddl-auto=update

gemini.api.key=
